import { Product } from "./types"

const baseDate = new Date("2025-01-01T00:00:00.000Z")

function daysAgo(days: number): string {
  const date = new Date(baseDate)
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Arca de Noé",
    description: "Un divertido juego de memoria y estrategia sobre la historia del Arca de Noé. Perfecto para desarrollar habilidades de concentración y aprender sobre la Biblia de una manera interactiva.",
    price: 24900,
    image_url: "/images/game-1.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 15,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(120),
  },
  {
    id: "2",
    name: "Familia Unida",
    description: "Trivia bíblica emocionante para toda la familia. Reúne a tus seres queridos y pon a prueba tus conocimientos de las Escrituras con cientos de preguntas divertidas y dinámicas grupales.",
    price: 29900,
    image_url: "/images/game-2.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 25,
    category: "Juegos Familiares",
    age_range: "6 - 12",
    created_at: daysAgo(115),
  },
  {
    id: "3",
    name: "Historias Bíblicas",
    description: "Aprende las historias más asombrosas de la Biblia jugando. Este juego de cartas desafía a los jugadores a ordenar cronológicamente los eventos clave del Antiguo y Nuevo Testamento.",
    price: 19900,
    image_url: "/images/game-3.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 30,
    category: "Juegos de Cartas",
    age_range: "6 - 12",
    created_at: daysAgo(110),
  },
  {
    id: "4",
    name: "Aventura de Fe",
    description: "Un profundo juego de mesa de estrategia y toma de decisiones basado en los viajes de los apóstoles. Supera desafíos, comparte la palabra y fortalece tu fe en cada turno.",
    price: 34900,
    image_url: "/images/game-4.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 10,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(105),
  },
  {
    id: "5",
    name: "Quiz Bíblico",
    description: "El juego de preguntas y respuestas rápido y divertido perfecto para jóvenes y campamentos. Ideal para romper el hielo y repasar las enseñanzas bíblicas con risas aseguradas.",
    price: 17900,
    image_url: "/images/game-5.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 40,
    category: "Juegos de Bolsillo",
    age_range: "12 - 120",
    created_at: daysAgo(100),
  },
  {
    id: "6",
    name: "David y Goliat",
    description: "Un juego de destreza y fe inspirado en el valiente David. Lanza, apunta y aprende sobre el coraje que viene de confiar en Dios frente a los gigantes de la vida.",
    price: 21900,
    image_url: "/images/game-1.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 18,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(95),
  },
  {
    id: "7",
    name: "Parábolas de Jesús",
    description: "Descubre las enseñanzas de Jesús a través de parábolas ilustradas. Une personajes, resuelve acertijos y reflexiona sobre valores como el perdón, la generosidad y el amor al prójimo.",
    price: 26900,
    image_url: "/images/game-2.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 22,
    category: "Juegos Familiares",
    age_range: "6 - 12",
    created_at: daysAgo(90),
  },
  {
    id: "8",
    name: "Reyes y Profetas",
    description: "Recorre la historia de Israel con reyes, profetas y momentos decisivos. Un juego de estrategia ligera ideal para profundizar en el Antiguo Testamento en familia.",
    price: 32900,
    image_url: "/images/game-3.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 12,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(85),
  },
  {
    id: "9",
    name: "Creación del Mundo",
    description: "Arma el universo día a día en este juego educativo para los más pequeños. Colores, animales y elementos de la creación en un formato simple y lleno de ternura.",
    price: 18900,
    image_url: "/images/game-4.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 35,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(80),
  },
  {
    id: "10",
    name: "Frutos del Espíritu",
    description: "Cartas y retos que invitan a practicar amor, paz, paciencia y bondad. Perfecto para grupos de jóvenes, células y reuniones familiares con dinámicas participativas.",
    price: 15900,
    image_url: "/images/game-5.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 45,
    category: "Juegos de Cartas",
    age_range: "6 - 12",
    created_at: daysAgo(75),
  },
  {
    id: "11",
    name: "Proverbios Sabios",
    description: "Pon a prueba tu sabiduría con citas y situaciones basadas en el libro de Proverbios. Ideal para adolescentes y adultos que disfrutan de debates y aprendizaje profundo.",
    price: 23900,
    image_url: "/images/game-1.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 20,
    category: "Juegos de Bolsillo",
    age_range: "12 - 120",
    created_at: daysAgo(70),
  },
  {
    id: "12",
    name: "Salmos de Alabanza",
    description: "Un juego musical y cooperativo que celebra la adoración. Combina retos creativos, reflexión y momentos de alabanza para toda la familia.",
    price: 27900,
    image_url: "/images/game-2.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 16,
    category: "Juegos Familiares",
    age_range: "6 - 12",
    created_at: daysAgo(65),
  },
  {
    id: "13",
    name: "Viaje por Israel",
    description: "Recorre ciudades bíblicas, completa misiones y descubre lugares sagrados en un tablero ilustrado. Estrategia moderada con partidas de 45 a 60 minutos.",
    price: 38900,
    image_url: "/images/game-3.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 8,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(60),
  },
  {
    id: "14",
    name: "Apóstoles en Acción",
    description: "Sigue los pasos de los discípulos después de Pentecostés. Misiones, cooperación y decisiones morales en un juego dinámico para jóvenes y adultos.",
    price: 31900,
    image_url: "/images/game-4.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 14,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(55),
  },
  {
    id: "15",
    name: "Jonás y la Ballena",
    description: "Aventura marina para niños con mecánicas de memoria y cooperación. Una forma tierna de contar la historia de Jonás y la importancia de obedecer a Dios.",
    price: 20900,
    image_url: "/images/game-5.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 28,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(50),
  },
  {
    id: "16",
    name: "Moisés y las Plagas",
    description: "Juego de cartas rápido sobre el Éxodo de Egipto. Aprende los eventos clave mientras compites por completar secuencias históricas.",
    price: 16900,
    image_url: "/images/game-1.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 32,
    category: "Juegos de Cartas",
    age_range: "6 - 12",
    created_at: daysAgo(45),
  },
  {
    id: "17",
    name: "Daniel en el Foso",
    description: "Cooperativo para niños: trabajen juntos para ayudar a Daniel y aprender sobre oración y valentía. Partidas cortas ideales para la hora del cuento.",
    price: 22900,
    image_url: "/images/game-2.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 19,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(40),
  },
  {
    id: "18",
    name: "Rut y Noemí",
    description: "Un juego de cartas sobre lealtad, amor familiar y provisión divina. Historia conmovedora adaptada para partidas ágiles de 20 minutos.",
    price: 18900,
    image_url: "/images/game-3.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 24,
    category: "Juegos de Cartas",
    age_range: "6 - 12",
    created_at: daysAgo(35),
  },
  {
    id: "19",
    name: "Estér y el Rey",
    description: "Intriga, valentía y fe en la corte persa. Un juego de deducción ligero para adolescentes y adultos basado en el libro de Ester.",
    price: 29900,
    image_url: "/images/game-4.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 11,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(30),
  },
  {
    id: "20",
    name: "Torre de Babel",
    description: "Construye, comunica y ríe con retos de cooperación y caos controlado. Perfecto para grupos grandes en retiros y eventos de iglesia.",
    price: 25900,
    image_url: "/images/game-5.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 17,
    category: "Juegos Familiares",
    age_range: "6 - 12",
    created_at: daysAgo(25),
  },
  {
    id: "21",
    name: "Jerusalén Antigua",
    description: "Explora el templo, los muros y la vida cotidiana en la ciudad santa. Tablero detallado con mecánicas de exploración para toda la familia.",
    price: 36900,
    image_url: "/images/game-1.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 9,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(20),
  },
  {
    id: "22",
    name: "Noé Construye",
    description: "Piezas grandes y reglas simples para armar el arca antes de la lluvia. Desarrolla motricidad fina y trabajo en equipo en los más pequeños.",
    price: 19900,
    image_url: "/images/game-2.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 26,
    category: "Juegos Infantiles",
    age_range: "2 - 5",
    created_at: daysAgo(15),
  },
  {
    id: "23",
    name: "Misioneros del Mundo",
    description: "Viaja por continentes llevando el evangelio en un juego educativo de geografía y misión. Ideal para escuelas dominicales y familias misioneras.",
    price: 28900,
    image_url: "/images/game-3.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 13,
    category: "Juegos Familiares",
    age_range: "6 - 12",
    created_at: daysAgo(10),
  },
  {
    id: "24",
    name: "Tabernáculo Sagrado",
    description: "Monta y aprende sobre el tabernáculo con piezas detalladas y tarjetas explicativas. Experiencia educativa profunda para jóvenes y adultos.",
    price: 41900,
    image_url: "/images/game-4.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 6,
    category: "Estrategia",
    age_range: "12 - 120",
    created_at: daysAgo(5),
  },
  {
    id: "25",
    name: "Fe y Obra",
    description: "Mini juego de bolsillo con retos prácticos de servicio y reflexión. Llévalo a cualquier reunión y activa conversaciones significativas en minutos.",
    price: 14900,
    image_url: "/images/game-5.jpg",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    stock: 50,
    category: "Juegos de Bolsillo",
    age_range: "12 - 120",
    created_at: daysAgo(1),
  },
]
